homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.Home, name='Home'),
    path('about_me/', views.about_me, name='about_me'),
    path('contacts/', views.contacts, name='contacts'),
    path('index/', views.index, name='index'),
    path('memories/', views.memories, name='memories'),
    path('base/', views.base, name='base'),
    path('navbar/', views.navbar, name='navbar'),
]

jadwal/urls.py
from django.urls import path
from .views import Join, delete, detail

urlpatterns = [
    path('', Join, name = 'Schedule'),
    path('detail/<int:pk>', detail, name='detail'),
    path('<int:pk>', delete, name = 'hapus'),
]

story_4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),
    path('jadwal/', include('jadwal.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

# Create your models here.
class Schedule(models.Model):
    matkul = models.CharField(blank=False, max_length= 100)
    dosen = models.CharField(blank=False, max_length= 100)
    sks = models.IntegerField(blank=False)
    deskripsi = models.CharField(blank=False, max_length= 150)
    sem = models.CharField(blank=False, max_length= 150)
    kelas = models.CharField(blank=False, max_length= 150, help_text ='Masukkan tahun semester, e.g 2019/2020')

# class Assg(models.Model):
#     tugas = models.CharField(blank= False, max_length=150)
#     deadline = models.DateTime(blank= False)

jadwal/forms.py
from django import forms

class SchedForm(forms.Form):
        matkul = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Mata Kuliah',
            'type' : 'text',
            'required' : True,
        }))
        dosen = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Nama Dosen',
            'type' : 'text',
            'required' : True,
        }))
        sks = forms.IntegerField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Jumlah sks',
            'type' : 'text',
            'required' : True,
        }))
        deskripsi = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Deskripsi Mata Kuliah',
            'type' : 'text',
            'required' : True,
        }))
        sem = forms.CharField(widget=forms.TextInput(attrs={
            'class' : 'form-control',
            'placeholder' : 'Semester',
            'type' : 'text',
            'required' : True,
        }))
        kelas = forms.CharField(widget=forms.TextInput(attrs={
                    'class' : 'form-control',
                    'placeholder' : 'Kelas',
                    'type' : 'text',
                    'required' : True,
        }))

homepage/views.py
from django.shortcuts import render

# Create your views here.
def about_me(request):
    return render(request, 'about_me.html')

def Home(request):
    return render(request, 'Home.html')

def contacts(request):
    return render(request, 'contacts.html')

def index(request):
    return render(request, 'index.html')

def memories(request):
    return render(request, 'memories.html')

def base(request):
    return render(request, 'base.html')

def navbar(request):
    return render(request, 'navbar.html')

jadwal/views.py
from django.shortcuts import render, redirect
from .models import Schedule as jadwal
#from .models import Assg as tugas
from .forms import SchedForm

# Create your views here.
def Join(request):
    if(request.method == "POST"):
        form = SchedForm(request.POST)
        if (form.is_valid()):
            form2 = jadwal()
            form2.matkul = form.cleaned_data["matkul"]
            form2.dosen = form.cleaned_data["dosen"]
            form2.sks = form.cleaned_data["sks"]
            form2.deskripsi = form.cleaned_data["deskripsi"]
            form2.sem = form.cleaned_data["sem"]
            form2.kelas = form.cleaned_data["kelas"]
            form2.save()
        return redirect ("/jadwal")
    else:
        form2 = jadwal.objects.all()
        form = SchedForm()
        form_dictio ={
             "form2" : form2,
             "form": form
        }
        return render(request, 'jadwal.html', form_dictio)

def delete(request, pk):
    if (request.method == "POST"):
        form = SchedForm(request.POST)
        if(form.is_valid()):
            form2 = jadwal()
            form2.matkul = form.cleaned_data["matkul"]
            form2.dosen = form.cleaned_data["dosen"]
            form2.sks = form.cleaned_data["sks"]
            form2.deskripsi = form.cleaned_data["deskripsi"]
            form2.sem = form.cleaned_data["sem"]
            form2.kelas = form.cleaned_data["kelas"]
            form2.save()
        return redirect ("/jadwal")
    else:
        jadwal.objects.filter(pk = pk).delete()
        form = SchedForm()
        data = jadwal.objects.all()
        form_dictio ={
            "form2" : data,
            "form": form
        }
        return render(request, 'jadwal.html', form_dictio)

def detail(request, pk):
    matkul = jadwal.objects.get(pk=pk)
    detail_dictio= {
        "matkul" : matkul,

    }
    return render(request, 'detail.html', detail_dictio)

homepage/templates/Home.html
{% extends 'base.html' %}
{% load static %}


{% block title %}<title> Upsynth </title> {% endblock %}
<!--<head>
    <meta charset="UTF-8">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'style_home.css'%}">
</head>-->
{%block style %} <link rel="stylesheet" type="text/css" href="{% static 'style_home.css'%}"> {% endblock%}
    {% block content %}
    <!--<div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">

        <div class="collapse navbar-collapse navbar-menubuilder" ;>
            <ul class="nav navbar-nav navbar-left" align="center">
                <li><img src="{% static 'logo copy.png' %} " width="30px" height="40px" ></li>

                <li><a href="{% url 'homepage:Home' %}">Home</a>
                </li>
                <li><a href="{% url 'homepage:about_me'%}">About Me</a>
                </li>
                <li><a href="{% url 'homepage:contacts'%}">Contacts</a>
                </li>
                <li><a href="{% url 'homepage:memories'%}">Memories</a>
                </li>
                <li><a href="{% url 'homepage:index'%}">Story-1</a>
                </li>
            </ul>
        </div>
    </div>
</div>-->
    <br>
    <br>
    <br>
    <br>
    <div class= "d-flex p-2" align="center">

            <img src="{% static 'hello copy.png'%}" alt="hello" width="300" height="100" align="center">
            <br>
            <img src="{% static 'ui.png'%}" alt="Photo Profile" width="" height="200" align="center"/>
        <h2>Nikita Jacey Natania</h2>
        <br>
        <p>17 November 2001</p>
        <p>Scorpion</p>
        <p>Class of Fasilkom UI 2023</p>
        <p>1906353933</p>
        <p>ENFP-T</p>
    </div>
    <hr>
    <h3 ><i>Recomendations--</i> </h3>
    <div class= "d-flex p-2" id="book" align="center">

        <br>
        <h4>BOOK OF THE MONTH</h4>
        <img src="{% static 'Pulang-Alt.jpg'%}" alt="Pulang" style="width:195px;height:290px; ;background: url(Pulang-Alt.jpg);box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25)">
        <div id="synopsis">
            <p>
            This book tells story about Indonesian history between 1965 and 1998 through the eyes of a
               family caught up in the tumultuoys events of the period.
               Dimas Suryo is a journalist with slight left-ish leanings,
               so it’s lucky that he’s out of the country in 1965 when a
               Communist coup fails, thereby avoiding the inevitable and
               bloody backlash. Though -- while he is free from the fear of
               arrest and torture, he can never go home... </p>
            <a href="https://tonysreadinglist.wordpress.com/2015/10/18/home-by-leila-s-chudori-review/"; style="font-size:13px;align: center;">by Tony’s Reading List, 2016.</a>
        </div>
    </div>
    <br>
    <BR>
    <h4 align="center"">SONGS OF THE MONTH</h4>
    <br>
    <div class="wrapper">
        <div align="center">
            <img src="{% static 'summum bonum.jpeg'%}" alt="summum bonum" style="position: relative; width: 150px; height: 150px;background: url(summum bonum.jpg); box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
        </div>
        <div align="center">
            <img src="{% static 'gilbert.jpeg'%}" alt="Alone Again Naturally" style="position: relative; width: 150px; height: 150px;background: url(summum bonum.jpg); box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
        </div>

        <div align="center">
            <i>Summum Bonum</i>
            by
            Sunset Rollercoaster
        </div>
        <div align="center">
            <i>Alone Again Naturally</i>
            by
            Gilbert O'Sullivan
        </div>


    </div>
    <br>
    <hr>
    <div class="logo">
    <div align="right">
        <img src="{% static 'logo copy.png'%}" alt="logo" style="width: 40 px; height: 80px">
    </div>
    <div align="left">
        <b>about the logo</b>
        <p>upsynth is a nickname that I frequently use. I colored it yellow because it represented happiness and joy!</p>
    </div>

</div>
    <br>
<footer class="footer">
    <div>
        <p align="center">Copyright © 2020 Nikita Jacey.</p>
    </div>
</footer>
{% endblock %}

homepage/templates/about_me.html
{% extends 'base.html' %}
{% load static %}


{% block title %}<title> Upsynth </title> {% endblock %}
    {%block style %}<link rel="stylesheet" type="text/css" href=" {% static 'style_about.css' %} "> {%endblock%}

<!--
    <div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">

            <div class="collapse navbar-collapse navbar-menubuilder" ;>
                <ul class="nav navbar-nav navbar-left" align="center">
                    <li><img src="{% static 'logo copy.png'%} " width="30px" height="40px" ></li>

                    <li><a href="{% url 'homepage:Home'%}">Home</a>
                    </li>
                    <li><a href="{% url 'homepage:about_me'%}">About Me</a>
                    </li>
                    <li><a href="{% url 'homepage:contacts'%}">Contacts</a>
                    </li>
                    <li><a href="{% url 'homepage:memories'%}">Memories</a>
                    </li>
                    <li><a href="{% url 'homepage:index'%}">Story-1</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>-->

{% block content %}
        <br>
        <br>
        <br>
        <br>

    <div CLASS="konten" id="about">
        <h1 style="color: black;"><b><i>ABOUT ME</i></b></h1>
        I’m a student that currently enrolled at the University of Indonesia majoring in System Information on 2nd semester.

        <br>
        <div>
            <h3><i>EXPERIENCES--</i></h3>
            <p>I have a lot of interest on creative field especially in design. I can operate Adobe Photoshop and sometimes Adobe Illustrator.</p>
            <p>Publication Division of Pancawarna 2018</p>

            <p>Head of Year Book Committee 2018</p>

            <p>Campaign Division of PEMIRA Fasilkom UI 2019</p>

            <p>Head of Visual Design Committee for Zona Kampus 2020</p>

            <p>HRD of DNC COMPFEST 12</p>
        </div>

    </div>
    <div class="kotak" style="color: white; font-size: 20px">
        <a href="https://drive.google.com/file/d/0B7ZGVy2Hi48cMURXRG9wczlsZDM0RTVwYTl1QWtmaFRQTHVn/view?usp=sharing" target="_blank">
        See my full CV here
        </a>
    </div>
    <div class ="konten" id="interest">
        <h3><i>INTEREST--</i></h3>
        <p>I also have interest in analog camera, I find it thrilling on the waiting process when developing the camera. Here’s a few pictures that I took</p>
        <div class="foto" id="baris1">
            <div><img src= "{% static 'BC5DB132-0B8A-4FC0-9A0A-D9E7C85025C6.jpeg'%}" width="200px" height="120px"> </div>
            <div><img src="{% static 'lab2625.jpg'%}" width="200px" height="120px"></div>
            <div><img src="{% static 'lab2622.jpg' %}" width="200px" height="120px"></div>
        <p><i>colored</i></p>
        </div>
        <br>
        <br>
        <br>
        <div class="foto" id="baris2">
            <div><img src="{% static 'lab2606.jpg'%}" width="200px" height="120px"> </div>
            <div><img src="{% static 'lab2610.jpg'%}" width="200px" height="120px"></div>
            <div><img src="{% static 'lab2620.jpg'%}" width="200px" height="120px"></div>
            <p><i>black & white</i></p>
        </div>
        <br>

<br>
<br>


    <div class="container">
        <p align="center">Copyright © 2020 Nikita Jacey.</p>
    </div>
        {%endblock%}

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}  {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css'%}">
    {%block style%} {% endblock %}

</head>
    {% block js%}
    {% endblock %}
<body>
{% include "navbar.html" %}
    {% block content %}

    {% endblock  %}


</body>
    {% block footer %}
    {% endblock %}

</html>

homepage/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block style%}<link rel="stylesheet" type="text/css" href="{% static 'style_contact.css'%}">{% endblock%}

{% block content%}
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
<div id="contact" style="color: black">
        <div id="email">
            EMAIL
            <p>nikita17jacey@gmail.com</p>
        </div>
     <br>
        <div><a href="https://www.instagram.com/nikita.natania/" target="_blank" style="color: black">INSTAGRAM</a></div>
            <br>
        <div><a href="id.pinterest.com/nktjcy/>PINTEREST" target="_blank "style="color: black"</a></div>

    <div><a href="https://www.linkedin.com/feed/?trk=guest_homepage-basic_nav-header-signin" target="_blank" style="color: black">LINKEDIN</a></div>
            <br>
        <div><a href="https://open.spotify.com/user/nktjcy?si=4hyYd67XTM6Oe3Pamhsibg" target="_blank" style="color: black">SPOTIFY</a></div>
    </div>
</

{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'story.css'%}"> {% endblock %}

{% block content %}
        <div id="header">
            <div id="back">
            <a href="{% url 'homepage:Home'%}"><h1>♡</h1> </a>
            </div>
            ✧･ﾟ: *✧･ﾟ:* Hello  *:･ﾟ✧*:･ﾟ✧
        </div>
    <br>
<br>

            <div id="profile">
                 <img src="{% static 'profile.png'%}" alt="Photo Profile" width="150" height="150" align="center"/>
                 <p>#111</p>
            </div>

            <div id="main">
                <h2>About me</h2>
                <table style="width:70%">
                    <tr>
                        <td>Name</td>
                        <td>Nikita Jacey Natania</td>
                    </tr>
                    <tr>
                        <td>NPM</td>
                        <td>1906353933</td>
                    </tr>
                    <tr>
                        <td>Student of</td>
                        <td>Fasilkom UI 2019 <a href="https://maung.id/nikita.jacey" target="_blank"> <i>MAUNG</i></a></td>
                    </tr>
                    <tr>
                        <td>Hobbies</td>
                         <td>Watching movies</td>
                </table>
                <br>
                <p><font size="6">"</font> I dont like pink <font size="6"> "</font></p>
                <br>
                <h2>Education</h2>
                <table style="width:100%">
                    <tr>
                        <td>SD Tarakanita 5</td>
                        <td>2007 — 2013</td>
                    </tr>
                    <tr>
                        <td>SMP Tarakanita 4</td>
                        <td>2013 — 2016</td>
                    </tr>
                    <tr>
                        <td>SMA Negeri 81 Jakarta</td>
                        <td>2016 — 2019</td>
                    </tr>
                    <tr>
                        <td>University of Indonesia</td>
                        <td>2019 — 2023 <i>expected</i></td>
                    </tr>
                </table>
                <br>
            </div>
            <div id="socmed">
                <h2>Social Media</h2>
                <a href="https://www.instagram.com/nikita.natania/" target="_blank">
                    <img src="{% static 'insta.png'%}" alt="Ig @nikita.natania" width="50" height="50" hspace="20"/>
                </a>
                <a href="https://www.facebook.com/nikita.jacey" target="_blank">
                    <img src="{% static 'fb.png'%}" alt="FB Nikita Jacey" width="50" height="50" hspace="20"/>
                </a>
                <a href="https://www.linkedin.com/in/nikita-j-539a92138" target="_blank">
                    <img src="{% static 'linked.png'%}" alt="LinkedIn Nikita Jacey" width="50" height="50" hspace="20" />
                </a>
                <a href=" https://www.youtube.com/channel/UCTOTE16syO0-yNZEP2whkuw" target="_blank">
                    <img src="{% static 'youtube.png'%}" alt="Youtube Nikita Jacey" width="50" height="50" hspace="20"/>
                </a>
                <a href="https://id.pinterest.com/nktjcy/" target="_blank">
                    <img src="{% static 'pinterest-logo.png'%}" alt="Pinterest Nikita Jacey" width="50" height="50" hspace="20"/>
                </a>
            </div>
    <br>
{% endblock %}

{% block footer %}
    <div id="footer1">
        Copyright &copy; 2020 Nikita Jacey.
    </div>
{%endblock%}

homepage/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upsynth</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css'%}">
</head>
<body>
    <div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">

        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-left" align="center">
                <li><img src="{% static 'logo copy.png' %} " width="30px" height="40px" ></li>

                <li><a href="{% url 'homepage:Home' %}">Home</a>
                </li>
                <li><a href="{% url 'homepage:about_me'%}">About Me</a>
                </li>
                <li><a href="{% url 'homepage:contacts'%}">Contacts</a>
                </li>
                <li><a href="{% url 'homepage:index'%}">Story-1</a>
                </li>
                <li><a href="jadwal/">Schedule</a>
                </li>
            </ul>
        </div>
    </div>
</div>

</body>

jadwal/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
    <meta charset="UTF-8">
    <title>Schedule</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static 'style_detail.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700&display=swap"rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&display=swap" rel="stylesheet">

</head>
<body>

<div id="DETAIL">
    <h1 style="align-text: center"><i>DETAIL//</i></h1>
    <a href="{% url 'Schedule' %}">
        <p> back</p>
    </a>
</div>
<div class="container" style="align: left">
    <div class="row">
        <div class="col">
            <form action='' method="POST">
                {% csrf_token %}
                {{ form }}
                <br>
            </form>
        </div>
        <div class="col" id="tulisan">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Mata Kuliah</th>
                    <th scope="col">Dosen</th>
                    <th scope="col">SKS</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Kelas</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">{{matkul.matkul}}</th>
                    <td>{{matkul.sks}}</td>
                    <td>{{matkul.dosen}}</td>
                    <td>{{matkul.deskripsi}}</td>
                    <td>{{matkul.sem}}</td>
                    <td>{{matkul.kelas}}</td>
                    {% comment %}
<!--                    <td>{{jadwal.sks}}</td>-->
<!--                    <td>{{jadwal.dosen}}</td>-->
<!--                    <td>{{jadwal.sks}}</td>-->
<!--                    <td>{{jadwal.deskripsi}}</td>-->
<!--                    <td>{{jadwal.sem}}</td>-->
<!--                    <td>{{jadwal.kelas}}</td>-->
                    {% endcomment %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>

jadwal/templates/jadwal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Schedule</title>
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static 'style_sched.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:700&display=swap"rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700&display=swap" rel="stylesheet">

</head>
<body>

<div id = "logo">
    <a href="{% url 'homepage:Home' %}">
    <img src="{% static 'logo copy.png' %} " width="40px" height="50px" >
    </a>
    <h1 style="align: center"><i>SCHEDULE--</i></h1>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <form action='' method="POST">
                {% csrf_token %}
                {{ form }}
                <br>
                <div class="centre-items">
                    <input type="submit" class="btn btn-primary" value="Add Schedule" style="background-color: black; border-color: black;">
                </div>
            </form>
        </div>
        <div class="col" id="tulisan">
            <table class="table">
                <thead>
                <tr>
                   <th scope="col">Mata Kuliah</th>
<!--                    <th scope="col">Dosen</th>-->
<!--                    <th scope="col">SKS</th>-->
<!--                    <th scope="col">Deskripsi</th>-->
<!--                    <th scope="col">Semester</th>-->
<!--                    <th scope="col">Kelas</th>-->
                </tr>
                </thead>
                <br>
                <tbody>
                {% for jadwal in form2 %}
                <tr>
                    <th scope="row">{{jadwal.matkul}}</th>

<!--                    <td>{{jadwal.sks}}</td>-->
<!--                    <td>{{jadwal.dosen}}</td>-->
<!--                    <td>{{jadwal.deskripsi}}</td>-->
<!--                    <td>{{jadwal.sem}}</td>-->
<!--                    <td>{{jadwal.kelas}}</td>-->

                    <td><a href="{% url 'hapus' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
                    <td><a href="{% url 'detail' pk=jadwal.pk %}"> <button class="btn btn-info"></button></a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
<br>
<div class="container">
    <p align="center">Copyright © 2020 Nikita Jacey.</p>
</div>
</html>